# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TEMPLATE-DEV-CONTAINER_prod

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: TEMPLATE-DEV-CONTAINER_dev
    volumes:
      - .:/TEMPLATE-DEV-CONTAINER
    command: [ "tail", "-f", "/dev/null" ]
